import os
import requests
from datetime import datetime
from flask import Flask, render_template, jsonify


app = Flask(__name__)


@app.route("/")
def perma_status(up="up!", message=""):
    """
    Show the status page with charts

    The required template is generated by index.py
    """
    try:
        with open(os.getenv('MAINTENANCE_FILE', 'maintenance.txt'), 'r') as f:
            up = f.readline()
            message = f.read()
    except FileNotFoundError:
        pass
    try:
        return render_template("index.html", up=up, message=message)
    except Exception:
        return jsonify({"error": "missing template"}), 500


def age(objects, now, f):
    return (
        now - datetime.strptime(
            f(
                [
                    o['creation_timestamp']
                    for o in objects if o['capture_time']
                ]
            ), "%Y-%m-%dT%H:%M:%S.%fZ"
        )
    ).total_seconds()


@app.route("/monitor")
def perma_monitor():
    """ hit the Perma API and get the last twenty captures for analysis """
    limit = 20
    thresholds = {"unfinished": 7, "statistic": 0.9}
    base = 'https://api.perma.cc/v1/public/archives'
    limit = 20
    offset = 0
    url = f'{base}?limit={limit}&offset={offset}'

    report = {"status": [], "messages": []}

    try:
        objects = requests.get(url).json()['objects']
    except Exception as e:
        report["status"].append("PROBLEM_PENDING")
        report["messages"].append(f"API unavailable: {e}")
        return jsonify(report=report)

    pending = sum(
        [
            any([
                "pending" in c['status']
                for c in o['captures']
                if not c['user_upload']
            ])
            for o in objects
        ]
    )

    # what is the ratio of seconds from now to the last completed capture to
    # the seconds from now to the oldest capture within {limit} captures ago?
    now = datetime.utcnow()
    if pending != limit:
        try:
            oldest = age(objects, now, min)
            newest = age(objects, now, max)
            statistic = newest / oldest
        except Exception as e:
            report["status"].append("PROBLEM_PENDING")
            report["messages"].append(f"Couldn't get capture ages: {e}")
            return jsonify(report=report)
        if statistic > thresholds["statistic"]:
            report["status"].append("PROBLEM_LOWUSAGE")
            msg = f"statistic for time to last successful capture) is {statistic}"
            report["messages"].append(msg)
    else:
        statistic = "n/a"

    if pending > thresholds["unfinished"]:
        report["status"].append("PROBLEM_PENDING")
        msg = f"{pending} uncompleted captures in the last {limit}"
        report["messages"].append(msg)

    if not report["status"]:
        report["status"] = ["OK"]

    output = {
        "unfinished": pending,
        "statistic": statistic,
        "report": report
    }
    return jsonify(**output)
