import os
from flask import Flask, render_template, jsonify
from dotenv import load_dotenv


app = Flask(__name__)
load_dotenv()

@app.route("/")
def perma_status(up="up!", message=""):
    """
    Show the status page with charts

    The required template is generated by index.py
    """
    try:
        with open(os.getenv('MAINTENANCE_FILE', 'maintenance.txt'), 'r') as f:
            up = f.readline()
            message = f.read()
    except FileNotFoundError:
        pass
    try:
        return render_template("index.html", up=up, message=message)
    except Exception:
        return jsonify({"error": "missing template"}), 500
